services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PWD=${DB_PWD}
    - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres:15-alpine"
    container_name: muj-prvni-container
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=toor
    - POSTGRES_DB=${DB_HOST}
    volumes:
       - db:/data/postgres-data
    ports:
      - "5432:5432"
    restart: unless-stopped
